// Traditional-Chinese names (and short explanations) for common US-GAAP /
// IFRS statement concepts. Keyed by prefixed concept name. Value is
// [name] or [name, explanation]. Concepts not listed fall back to the
// filer's English label in the UI.

import { CUSTOM, DESCRIPTIONS, MORE } from './zh-more.js';

const T = {
  // ---------- 報表標題 / 段落 ----------
  'us-gaap:StatementOfFinancialPositionAbstract': ['資產負債表'],
  'us-gaap:IncomeStatementAbstract': ['損益表'],
  'us-gaap:StatementOfIncomeAndComprehensiveIncomeAbstract': ['綜合損益表'],
  'us-gaap:StatementOfCashFlowsAbstract': ['現金流量表'],
  'us-gaap:StatementOfStockholdersEquityAbstract': ['股東權益變動表'],
  'us-gaap:EquityAbstract': ['權益'],
  'us-gaap:AssetsAbstract': ['資產'],
  'us-gaap:AssetsCurrentAbstract': ['流動資產'],
  'us-gaap:AssetsNoncurrentAbstract': ['非流動資產'],
  'us-gaap:LiabilitiesAndStockholdersEquityAbstract': ['負債及股東權益'],
  'us-gaap:LiabilitiesAbstract': ['負債'],
  'us-gaap:LiabilitiesCurrentAbstract': ['流動負債'],
  'us-gaap:LiabilitiesNoncurrentAbstract': ['非流動負債'],
  'us-gaap:StockholdersEquityAbstract': ['股東權益'],
  'us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterestAbstract': ['權益（含非控制權益）'],
  'us-gaap:RevenuesAbstract': ['收入'],
  'us-gaap:CostsAndExpensesAbstract': ['成本及費用'],
  'us-gaap:CostOfRevenueAbstract': ['營業成本'],
  'us-gaap:OperatingExpensesAbstract': ['營業費用'],
  'us-gaap:EarningsPerShareAbstract': ['每股盈餘'],
  'us-gaap:WeightedAverageNumberOfSharesOutstandingAbstract': ['加權平均流通在外股數'],
  'us-gaap:WeightedAverageNumberOfSharesOutstandingDilutedDisclosureItemsAbstract': ['稀釋加權平均股數'],
  'us-gaap:ComprehensiveIncomeNetOfTaxAbstract': ['綜合損益'],
  'us-gaap:OtherComprehensiveIncomeLossNetOfTaxPeriodIncreaseDecreaseAbstract': ['其他綜合損益'],
  'us-gaap:OtherComprehensiveIncomeAvailableForSaleSecuritiesAdjustmentNetOfTaxPeriodIncreaseDecreaseAbstract': ['備供出售證券未實現損益變動'],
  'us-gaap:OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentBeforeReclassificationAdjustmentsNetOfTaxAbstract': ['備供出售證券未實現損益（重分類前）'],
  'us-gaap:OtherComprehensiveIncomeDerivativesQualifyingAsHedgesNetOfTaxPeriodIncreaseDecreaseAbstract': ['現金流量避險損益變動'],
  'us-gaap:OtherComprehensiveIncomeDerivativesQualifyingAsHedgesTaxPortionAttributableToParentAbstract': ['避險損益之所得稅'],
  'us-gaap:NetCashProvidedByUsedInOperatingActivitiesAbstract': ['營業活動之現金流量'],
  'us-gaap:NetCashProvidedByUsedInInvestingActivitiesAbstract': ['投資活動之現金流量'],
  'us-gaap:NetCashProvidedByUsedInFinancingActivitiesAbstract': ['籌資活動之現金流量'],
  'us-gaap:NetCashProvidedByUsedInOperatingActivitiesContinuingOperationsAbstract': ['營業活動之現金流量（繼續營業）'],
  'us-gaap:NetCashProvidedByUsedInInvestingActivitiesContinuingOperationsAbstract': ['投資活動之現金流量（繼續營業）'],
  'us-gaap:NetCashProvidedByUsedInFinancingActivitiesContinuingOperationsAbstract': ['籌資活動之現金流量（繼續營業）'],
  'us-gaap:AdjustmentsToReconcileNetIncomeLossToCashProvidedByUsedInOperatingActivitiesAbstract': ['調整項目', '將淨利調節為營業活動現金流量的非現金項目'],
  'us-gaap:IncreaseDecreaseInOperatingCapitalAbstract': ['營業資產及負債之變動'],
  'us-gaap:SupplementalCashFlowInformationAbstract': ['現金流量補充資訊'],
  'us-gaap:CashFlowNoncashInvestingAndFinancingActivitiesDisclosureAbstract': ['不影響現金流量之投資及籌資活動'],
  'us-gaap:NoncashInvestingAndFinancingItemsAbstract': ['非現金投資及籌資項目'],
  'us-gaap:AdditionalCashFlowElementsInvestingActivitiesAbstract': ['其他投資活動'],
  'us-gaap:AdditionalCashFlowElementsFinancingActivitiesAbstract': ['其他籌資活動'],
  'us-gaap:ProceedsFromSaleAndMaturityOfHeldToMaturitySecuritiesAbstract': ['持有至到期證券收回'],
  'us-gaap:ProceedsFromSaleAndMaturityOfAvailableForSaleSecuritiesAbstract': ['備供出售證券出售及到期'],
  'us-gaap:InterestPaidAbstract': ['支付利息'],
  'us-gaap:LeaseCostAbstract': ['租賃成本'],
  'us-gaap:CashAndCashEquivalentsAbstract': ['現金及約當現金'],
  'us-gaap:InventoryNetAbstract': ['存貨'],
  'us-gaap:BalanceSheetRelatedDisclosuresAbstract': ['資產負債表相關揭露'],
  'us-gaap:NoninterestExpenseAbstract': ['非利息費用'],

  // ---------- 資產 ----------
  'us-gaap:CashAndCashEquivalentsAtCarryingValue': ['現金及約當現金', '現金與三個月內到期、流動性極高的短期投資'],
  'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents': ['現金、約當現金及受限制現金', '現金流量表期初/期末餘額，包含受限制現金'],
  'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations': ['現金、約當現金及受限制現金（含停業單位）'],
  'us-gaap:RestrictedCashAndCashEquivalents': ['受限制現金及約當現金'],
  'us-gaap:CashAndDueFromBanks': ['現金及存放銀行同業'],
  'us-gaap:InterestBearingDepositsInBanks': ['存放銀行之附息存款'],
  'us-gaap:MarketableSecuritiesCurrent': ['有價證券（流動）', '一年內可變現的債券、股票等投資'],
  'us-gaap:MarketableSecuritiesNoncurrent': ['有價證券（非流動）'],
  'us-gaap:MarketableSecurities': ['有價證券'],
  'us-gaap:ShortTermInvestments': ['短期投資'],
  'us-gaap:OtherShortTermInvestments': ['其他短期投資'],
  'us-gaap:CashCashEquivalentsAndShortTermInvestments': ['現金、約當現金及短期投資合計'],
  'us-gaap:DebtSecuritiesCurrent': ['債務證券（流動）'],
  'us-gaap:DebtSecuritiesAvailableForSaleExcludingAccruedInterest': ['備供出售債務證券'],
  'us-gaap:DebtSecuritiesAvailableForSaleAmortizedCostExcludingAccruedInterestAfterAllowanceForCreditLoss': ['備供出售債務證券（攤銷後成本）'],
  'us-gaap:DebtSecuritiesHeldToMaturityExcludingAccruedInterestAfterAllowanceForCreditLoss': ['持有至到期債務證券（淨額）'],
  'us-gaap:EquitySecuritiesFvNi': ['權益證券（透過損益按公允價值衡量）'],
  'us-gaap:AccountsReceivableNetCurrent': ['應收帳款淨額', '已扣除備抵呆帳的應收帳款'],
  'us-gaap:ReceivablesNetCurrent': ['應收款項淨額'],
  'us-gaap:NontradeReceivablesCurrent': ['非營業應收款'],
  'us-gaap:AllowanceForDoubtfulAccountsReceivableCurrent': ['備抵呆帳'],
  'us-gaap:InventoryNet': ['存貨', '原料、在製品與製成品'],
  'us-gaap:EnergyRelatedInventory': ['能源相關存貨'],
  'us-gaap:InventoryPartsAndComponentsNetOfReserves': ['材料及零件存貨'],
  'us-gaap:PrepaidExpenseAndOtherAssetsCurrent': ['預付費用及其他流動資產'],
  'us-gaap:OtherAssetsCurrent': ['其他流動資產'],
  'us-gaap:AssetsCurrent': ['流動資產合計', '一年內可轉換為現金或耗用的資產'],
  'us-gaap:PropertyPlantAndEquipmentNet': ['不動產、廠房及設備淨額', '固定資產扣除累計折舊'],
  'us-gaap:PropertyPlantAndEquipmentAndFinanceLeaseRightOfUseAssetAfterAccumulatedDepreciationAndAmortization': ['不動產、廠房及設備（含融資租賃使用權資產）淨額'],
  'us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment': ['累計折舊'],
  'us-gaap:OperatingLeaseRightOfUseAsset': ['營業租賃使用權資產', '承租人依租約取得的使用權'],
  'us-gaap:Goodwill': ['商譽', '收購價格超過被收購公司可辨認淨資產公允價值的部分'],
  'us-gaap:IntangibleAssetsNetExcludingGoodwill': ['無形資產淨額（不含商譽）'],
  'us-gaap:FiniteLivedIntangibleAssetsNet': ['有限耐用年限無形資產淨額'],
  'us-gaap:IndefiniteLivedTrademarks': ['非確定年限商標'],
  'us-gaap:DeferredIncomeTaxAssetsNet': ['遞延所得稅資產', '未來可抵減所得稅的暫時性差異'],
  'us-gaap:OtherLongTermInvestments': ['其他長期投資'],
  'us-gaap:LongTermInvestments': ['長期投資'],
  'us-gaap:LongTermInvestmentsAndReceivablesNet': ['長期投資及應收款淨額'],
  'us-gaap:EquityMethodInvestments': ['採用權益法之投資'],
  'us-gaap:OtherAssetsNoncurrent': ['其他非流動資產'],
  'us-gaap:OtherAssets': ['其他資產'],
  'us-gaap:AssetsNoncurrent': ['非流動資產合計'],
  'us-gaap:Assets': ['資產總額', '公司擁有或控制、預期帶來經濟效益的全部資源'],
  'us-gaap:DeferredCostsLeasingNetNoncurrent': ['遞延租賃成本（非流動）'],
  'us-gaap:CryptoAssetFairValueNoncurrent': ['加密資產（非流動）'],
  'us-gaap:AssetsOfDisposalGroupIncludingDiscontinuedOperation': ['待處分資產'],
  'us-gaap:FederalFundsSoldAndSecuritiesPurchasedUnderAgreementsToResell': ['拆放同業及附賣回證券'],
  'us-gaap:SecuritiesBorrowed': ['借入證券'],
  'us-gaap:FinancingReceivableExcludingAccruedInterestAfterAllowanceForCreditLoss': ['放款淨額'],
  'us-gaap:FinancingReceivableAllowanceForCreditLossExcludingAccruedInterest': ['放款備抵損失'],
  'us-gaap:FederalFundsSoldAndSecuritiesBorrowedOrPurchasedUnderAgreementsToResellFairValueDisclosure': ['拆放同業及附賣回證券（公允價值）'],
  'us-gaap:SecuritiesBorrowedFairValueDisclosure': ['借入證券（公允價值）'],
  'us-gaap:LoansReceivableFairValueDisclosure': ['放款（公允價值）'],
  'us-gaap:OtherAssetsFairValueDisclosure': ['其他資產（公允價值）'],

  // ---------- 負債 ----------
  'us-gaap:AccountsPayableCurrent': ['應付帳款', '因進貨或勞務而應付給供應商的款項'],
  'us-gaap:AccountsPayableAndAccruedLiabilitiesCurrent': ['應付帳款及應計負債'],
  'us-gaap:AccountsPayableAndAccruedLiabilitiesCurrentAndNoncurrent': ['應付帳款及應計負債'],
  'us-gaap:AccountsPayableAndAccruedLiabilitiesFairValueDisclosure': ['應付帳款及應計負債（公允價值）'],
  'us-gaap:AccruedLiabilitiesCurrent': ['應計負債', '已發生但尚未支付的費用'],
  'us-gaap:EmployeeRelatedLiabilitiesCurrent': ['應付員工相關款項'],
  'us-gaap:AccruedIncomeTaxesCurrent': ['應付所得稅'],
  'us-gaap:AccruedIncomeTaxesNoncurrent': ['長期應付所得稅'],
  'us-gaap:ContractWithCustomerLiabilityCurrent': ['合約負債（流動）', '已收款但尚未履行義務的預收收入'],
  'us-gaap:ContractWithCustomerLiabilityNoncurrent': ['合約負債（非流動）'],
  'us-gaap:OtherLiabilitiesCurrent': ['其他流動負債'],
  'us-gaap:CommercialPaper': ['商業本票'],
  'us-gaap:ShortTermBorrowings': ['短期借款'],
  'us-gaap:ShorttermDebtFairValue': ['短期借款（公允價值）'],
  'us-gaap:DebtCurrent': ['一年內到期之債務'],
  'us-gaap:LongTermDebtCurrent': ['一年內到期之長期債務'],
  'us-gaap:LongTermDebtAndCapitalLeaseObligationsCurrent': ['一年內到期之長期債務及租賃負債'],
  'us-gaap:NotesAndLoansPayable': ['應付票據及借款'],
  'us-gaap:LiabilitiesCurrent': ['流動負債合計', '一年內需清償的債務'],
  'us-gaap:LongTermDebtNoncurrent': ['長期債務', '一年以上到期的借款及公司債'],
  'us-gaap:LongTermDebtAndCapitalLeaseObligations': ['長期債務及租賃負債'],
  'us-gaap:LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities': ['長期債務（含一年內到期）'],
  'us-gaap:LongTermDebtFairValue': ['長期債務（公允價值）'],
  'us-gaap:OperatingLeaseLiabilityNoncurrent': ['營業租賃負債（非流動）'],
  'us-gaap:DeferredIncomeTaxLiabilitiesNet': ['遞延所得稅負債'],
  'us-gaap:PensionAndOtherPostretirementDefinedBenefitPlansLiabilitiesNoncurrent': ['退休金及其他退休後給付負債'],
  'us-gaap:OtherLiabilitiesNoncurrent': ['其他非流動負債'],
  'us-gaap:OtherLiabilities': ['其他負債'],
  'us-gaap:LiabilitiesNoncurrent': ['非流動負債合計'],
  'us-gaap:Liabilities': ['負債總額'],
  'us-gaap:CommitmentsAndContingencies': ['承諾及或有事項', '附註揭露的合約承諾與潛在義務，通常不列金額'],
  'us-gaap:LiabilitiesOfDisposalGroupIncludingDiscontinuedOperation': ['待處分負債'],
  'us-gaap:Deposits': ['存款'],
  'us-gaap:DepositsFairValueDisclosure': ['存款（公允價值）'],
  'us-gaap:FederalFundsPurchasedAndSecuritiesSoldUnderAgreementsToRepurchase': ['拆入同業及附買回證券'],
  'us-gaap:FederalFundsPurchasedAndSecuritiesLoanedOrSoldUnderAgreementsToRepurchaseFairValueDisclosure': ['拆入同業及附買回證券（公允價值）'],
  'us-gaap:TradingLiabilities': ['交易負債'],
  'us-gaap:BeneficialInterest': ['受益權'],
  'us-gaap:TemporaryEquityCarryingAmountIncludingPortionAttributableToNoncontrollingInterests': ['暫時性權益', '可贖回、列於負債與權益之間的股權'],
  'us-gaap:RedeemableNoncontrollingInterestEquityCarryingAmount': ['可贖回非控制權益'],

  // ---------- 權益 ----------
  'us-gaap:PreferredStockValue': ['特別股股本'],
  'us-gaap:PreferredStockValueOutstanding': ['流通在外特別股'],
  'us-gaap:PreferredStockIncludingAdditionalPaidInCapitalNetOfDiscount': ['特別股（含資本公積）'],
  'us-gaap:ConvertiblePreferredStockNonredeemableOrRedeemableIssuerOptionValue': ['可轉換特別股'],
  'us-gaap:PreferredStockSharesAuthorized': ['特別股核定股數'],
  'us-gaap:PreferredStockSharesIssued': ['特別股已發行股數'],
  'us-gaap:PreferredStockSharesOutstanding': ['特別股流通在外股數'],
  'us-gaap:PreferredStockParOrStatedValuePerShare': ['特別股每股面額'],
  'us-gaap:PreferredStockDividendRatePercentage': ['特別股股利率'],
  'us-gaap:PreferredStockLiquidationPreference': ['特別股清算優先權'],
  'us-gaap:CommonStockValue': ['普通股股本'],
  'us-gaap:CommonStockNoParValue': ['普通股（無面額）'],
  'us-gaap:CommonStocksIncludingAdditionalPaidInCapital': ['普通股股本及資本公積'],
  'us-gaap:CommonStockSharesAuthorized': ['普通股核定股數'],
  'us-gaap:CommonStockSharesIssued': ['普通股已發行股數'],
  'us-gaap:CommonStockSharesOutstanding': ['普通股流通在外股數'],
  'us-gaap:CommonStockParOrStatedValuePerShare': ['普通股每股面額'],
  'us-gaap:SharesIssued': ['已發行股數'],
  'us-gaap:AdditionalPaidInCapital': ['資本公積', '股東投入超過股本面額的金額'],
  'us-gaap:AdditionalPaidInCapitalCommonStock': ['資本公積—普通股'],
  'us-gaap:TreasuryStockCommonValue': ['庫藏股', '公司買回尚未註銷的自家股票，為權益減項'],
  'us-gaap:TreasuryStockValue': ['庫藏股'],
  'us-gaap:TreasuryStockCommonShares': ['庫藏股股數'],
  'us-gaap:RetainedEarningsAccumulatedDeficit': ['保留盈餘（累積虧損）', '歷年累積淨利扣除已分配股利'],
  'us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax': ['累積其他綜合損益', '未實現的匯率、證券評價、避險等損益累計數'],
  'us-gaap:StockholdersEquity': ['股東權益合計', '歸屬於母公司股東的權益'],
  'us-gaap:StockholdersEquityOther': ['其他權益'],
  'us-gaap:MinorityInterest': ['非控制權益', '子公司中不屬於母公司的股權'],
  'us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest': ['權益總額（含非控制權益）'],
  'us-gaap:LiabilitiesAndStockholdersEquity': ['負債及權益總額'],

  // ---------- 損益表 ----------
  'us-gaap:Revenues': ['營業收入', '本期銷售商品或提供勞務的總收入'],
  'us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax': ['營業收入', '與客戶合約之收入，不含代收稅款'],
  'us-gaap:RevenuesNetOfInterestExpense': ['淨收益（扣除利息費用）'],
  'us-gaap:CostOfRevenue': ['營業成本'],
  'us-gaap:CostOfGoodsAndServicesSold': ['銷貨及勞務成本', '產生收入直接投入的材料、人工與製造費用'],
  'us-gaap:GrossProfit': ['毛利', '營業收入減營業成本'],
  'us-gaap:ResearchAndDevelopmentExpense': ['研發費用'],
  'us-gaap:SellingGeneralAndAdministrativeExpense': ['銷售及管理費用'],
  'us-gaap:SellingAndMarketingExpense': ['銷售及行銷費用'],
  'us-gaap:MarketingExpense': ['行銷費用'],
  'us-gaap:MarketingAndAdvertisingExpense': ['行銷及廣告費用'],
  'us-gaap:GeneralAndAdministrativeExpense': ['管理費用'],
  'us-gaap:OperatingExpenses': ['營業費用合計'],
  'us-gaap:CostsAndExpenses': ['成本及費用合計'],
  'us-gaap:OtherCostAndExpenseOperating': ['其他營業成本及費用'],
  'us-gaap:OtherOperatingIncomeExpenseNet': ['其他營業收益（費損）淨額'],
  'us-gaap:ExplorationExpense': ['探勘費用'],
  'us-gaap:CapitalizedExploratoryWellCostChargedToExpense1': ['探勘井成本轉列費用'],
  'us-gaap:TaxesOther': ['其他稅捐'],
  'us-gaap:OperatingIncomeLoss': ['營業利益', '本業獲利：毛利減營業費用'],
  'us-gaap:NonoperatingIncomeExpense': ['營業外收支淨額'],
  'us-gaap:OtherNonoperatingIncomeExpense': ['其他營業外收支'],
  'us-gaap:InvestmentIncomeInterest': ['利息收入'],
  'us-gaap:InterestExpense': ['利息費用'],
  'us-gaap:InterestExpenseNonoperating': ['利息費用（營業外）'],
  'us-gaap:InterestIncomeOperating': ['利息收入'],
  'us-gaap:InterestExpenseOperating': ['利息費用'],
  'us-gaap:InterestIncomeExpenseNet': ['利息淨收益'],
  'us-gaap:NoninterestIncome': ['非利息收入'],
  'us-gaap:NoninterestIncomeOther': ['其他非利息收入'],
  'us-gaap:NoninterestExpense': ['非利息費用'],
  'us-gaap:OtherNoninterestExpense': ['其他非利息費用'],
  'us-gaap:InvestmentBankingRevenue': ['投資銀行收入'],
  'us-gaap:PrincipalTransactionsRevenue': ['自營交易收入'],
  'us-gaap:ProvisionForLoanLeaseAndOtherLosses': ['放款損失提列'],
  'us-gaap:LaborAndRelatedExpense': ['人事費用'],
  'us-gaap:OccupancyNet': ['房屋及設備費用'],
  'us-gaap:CommunicationsAndInformationTechnology': ['通訊及資訊科技費用'],
  'us-gaap:ProfessionalAndContractServicesExpense': ['專業及外包服務費用'],
  'us-gaap:DebtAndEquitySecuritiesGainLoss': ['債務及權益證券損益'],
  'us-gaap:DebtSecuritiesAvailableForSaleRealizedGainLoss': ['備供出售證券已實現損益'],
  'us-gaap:GainLossOnInvestments': ['投資損益'],
  'us-gaap:UnrealizedGainLossOnInvestments': ['投資未實現損益'],
  'us-gaap:IncomeLossFromEquityMethodInvestments': ['採用權益法認列之投資損益'],
  'us-gaap:IncomeLossFromEquityMethodInvestmentsNetOfDividendsOrDistributions': ['權益法投資損益（扣除股利）'],
  'us-gaap:ForeignCurrencyTransactionGainLossBeforeTax': ['外幣兌換損益'],
  'us-gaap:ForeignCurrencyTransactionGainLossUnrealized': ['未實現外幣兌換損益'],
  'us-gaap:GainLossOnSaleOfOtherAssets': ['處分其他資產損益'],
  'us-gaap:NetPeriodicDefinedBenefitsExpenseReversalOfExpenseExcludingServiceCostComponent': ['退休金淨成本（不含服務成本）'],
  'us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest': ['稅前淨利', '所得稅前的利益'],
  'us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments': ['稅前淨利（權益法投資損益前）'],
  'us-gaap:IncomeTaxExpenseBenefit': ['所得稅費用'],
  'us-gaap:ProfitLoss': ['本期淨利（含非控制權益）'],
  'us-gaap:NetIncomeLoss': ['本期淨利', '歸屬於母公司股東的稅後淨利'],
  'us-gaap:NetIncomeLossAttributableToNoncontrollingInterest': ['歸屬於非控制權益之淨利'],
  'us-gaap:NetIncomeLossAvailableToCommonStockholdersBasic': ['歸屬於普通股股東之淨利（基本）'],
  'us-gaap:NetIncomeLossAvailableToCommonStockholdersDiluted': ['歸屬於普通股股東之淨利（稀釋）'],
  'us-gaap:PreferredStockDividendsIncomeStatementImpact': ['特別股股利'],
  'us-gaap:TemporaryEquityNetIncome': ['歸屬於暫時性權益之淨利'],
  'us-gaap:EarningsPerShareBasic': ['基本每股盈餘', '淨利除以加權平均流通在外股數'],
  'us-gaap:EarningsPerShareDiluted': ['稀釋每股盈餘', '假設所有可轉換工具皆轉換後的每股盈餘'],
  'us-gaap:WeightedAverageNumberOfSharesOutstandingBasic': ['加權平均股數（基本）'],
  'us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding': ['加權平均股數（稀釋）'],
  'us-gaap:WeightedAverageNumberDilutedSharesOutstandingAdjustment': ['稀釋性潛在普通股'],
  'us-gaap:CommonStockDividendsPerShareDeclared': ['每股宣告股利'],

  // ---------- 綜合損益 ----------
  'us-gaap:ComprehensiveIncomeNetOfTax': ['本期綜合損益總額', '淨利加其他綜合損益'],
  'us-gaap:ComprehensiveIncomeNetOfTaxIncludingPortionAttributableToNoncontrollingInterest': ['綜合損益總額（含非控制權益）'],
  'us-gaap:ComprehensiveIncomeNetOfTaxAttributableToNoncontrollingInterest': ['歸屬於非控制權益之綜合損益'],
  'us-gaap:OtherComprehensiveIncomeLossNetOfTax': ['其他綜合損益（稅後）'],
  'us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent': ['其他綜合損益（稅後）', '不透過損益的權益變動，如外幣換算、證券評價、避險'],
  'us-gaap:OtherComprehensiveIncomeOtherNetOfTax': ['其他綜合損益—其他'],
  'us-gaap:OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax': ['外幣換算調整'],
  'us-gaap:OtherComprehensiveIncomeForeignCurrencyTransactionAndTranslationAdjustmentNetOfTaxPortionAttributableToParent': ['外幣換算調整'],
  'us-gaap:OtherComprehensiveIncomeForeignCurrencyTransactionAndTranslationGainLossArisingDuringPeriodNetOfTax': ['本期外幣換算損益'],
  'us-gaap:OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationReclassificationAdjustmentFromAOCIRealizedUponSaleOrLiquidationNetOfTax': ['外幣換算重分類調整'],
  'us-gaap:OtherComprehensiveIncomeLossForeignCurrencyTranslationAdjustmentTax': ['外幣換算調整之所得稅'],
  'us-gaap:OtherComprehensiveIncomeForeignCurrencyTranslationGainLossArisingDuringPeriodTax': ['本期外幣換算損益之所得稅'],
  'us-gaap:OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax': ['備供出售證券未實現損益'],
  'us-gaap:OtherComprehensiveIncomeAvailableforsaleSecuritiesAdjustmentNetOfTaxPortionAttributableToParent': ['備供出售證券未實現損益'],
  'us-gaap:OtherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodNetOfTax': ['本期證券未實現持有損益'],
  'us-gaap:OtherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodTax': ['本期證券未實現損益之所得稅'],
  'us-gaap:OtherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIForSaleOfSecuritiesNetOfTax': ['出售證券重分類至損益'],
  'us-gaap:OtherComprehensiveIncomeLossAvailableForSaleSecuritiesTax': ['備供出售證券損益之所得稅'],
  'us-gaap:OtherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationAndTax': ['現金流量避險損益'],
  'us-gaap:OtherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationAndTaxParent': ['現金流量避險損益'],
  'us-gaap:OtherComprehensiveIncomeLossCashFlowHedgeGainLossBeforeReclassificationAfterTax': ['本期現金流量避險損益'],
  'us-gaap:OtherComprehensiveIncomeLossCashFlowHedgeGainLossReclassificationAfterTax': ['現金流量避險重分類至損益'],
  'us-gaap:OtherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationTax': ['現金流量避險損益之所得稅'],
  'us-gaap:OtherComprehensiveIncomeLossDerivativeExcludedComponentIncreaseDecreaseAfterAdjustmentsAndTaxParent': ['衍生工具排除組成部分損益'],
  'us-gaap:OtherComprehensiveIncomeLossPensionAndOtherPostretirementBenefitPlansAdjustmentNetOfTax': ['退休金及退休後給付計畫調整'],
  'us-gaap:OtherComprehensiveIncomeDefinedBenefitPlansAdjustmentNetOfTaxPortionAttributableToParent': ['確定福利計畫調整'],
  'us-gaap:OtherComprehensiveIncomeLossFinancialLiabilityFairValueOptionAfterTaxAndReclassificationAdjustmentAttributableToParent': ['金融負債自身信用風險變動'],

  // ---------- 權益變動表 ----------
  'us-gaap:StockIssuedDuringPeriodValueNewIssues': ['發行新股'],
  'us-gaap:StockIssuedDuringPeriodSharesNewIssues': ['發行新股股數'],
  'us-gaap:StockRepurchasedAndRetiredDuringPeriodValue': ['買回並註銷股份'],
  'us-gaap:StockRepurchasedAndRetiredDuringPeriodShares': ['買回並註銷股數'],
  'us-gaap:StockRedeemedOrCalledDuringPeriodValue': ['贖回股份'],
  'us-gaap:TreasuryStockValueAcquiredCostMethod': ['買回庫藏股'],
  'us-gaap:TreasuryStockSharesAcquired': ['買回庫藏股股數'],
  'us-gaap:StockIssuedDuringPeriodValueTreasuryStockReissued': ['庫藏股再發行'],
  'us-gaap:AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue': ['股份基礎給付酬勞', '員工認股權、限制型股票等以股票支付的薪酬'],
  'us-gaap:AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationAndExerciseOfStockOptions': ['股份基礎給付及認股權執行'],
  'us-gaap:AdjustmentsToAdditionalPaidInCapitalOther': ['資本公積其他調整'],
  'us-gaap:AdjustmentsToAdditionalPaidInCapitalDividendsInExcessOfRetainedEarnings': ['超過保留盈餘之股利（沖減資本公積）'],
  'us-gaap:AdjustmentsRelatedToTaxWithholdingForShareBasedCompensation': ['股份基礎給付之代扣稅款'],
  'us-gaap:SharesPaidForTaxWithholdingForShareBasedCompensation': ['代扣稅款而收回之股數'],
  'us-gaap:Dividends': ['股利'],
  'us-gaap:DividendsCommonStock': ['普通股股利'],
  'us-gaap:DividendsCommonStockCash': ['普通股現金股利'],
  'us-gaap:DividendsPreferredStockCash': ['特別股現金股利'],
  'us-gaap:NoncontrollingInterestIncreaseFromSaleOfParentEquityInterest': ['出售子公司股權予非控制權益'],
  'us-gaap:MinorityInterestDecreaseFromDistributionsToNoncontrollingInterestHolders': ['分配予非控制權益'],
  'us-gaap:MinorityInterestDecreaseFromRedemptions': ['贖回非控制權益'],

  // ---------- 現金流量表：營業活動 ----------
  'us-gaap:DepreciationDepletionAndAmortization': ['折舊、折耗及攤銷', '非現金費用，調節時加回'],
  'us-gaap:Depreciation': ['折舊'],
  'us-gaap:DepreciationAmortizationAndAccretionNet': ['折舊、攤銷及增額'],
  'us-gaap:ShareBasedCompensation': ['股份基礎給付酬勞', '非現金費用，調節時加回'],
  'us-gaap:DeferredIncomeTaxExpenseBenefit': ['遞延所得稅'],
  'us-gaap:DeferredIncomeTaxesAndTaxCredits': ['遞延所得稅及稅額抵減'],
  'us-gaap:InventoryWriteDown': ['存貨跌價損失'],
  'us-gaap:OtherNoncashIncomeExpense': ['其他非現金項目'],
  'us-gaap:OtherOperatingActivitiesCashFlowStatement': ['其他營業活動'],
  'us-gaap:IncreaseDecreaseInAccountsReceivable': ['應收帳款（增加）減少'],
  'us-gaap:IncreaseDecreaseInAccountsReceivableAndOtherOperatingAssets': ['應收帳款及其他營業資產變動'],
  'us-gaap:IncreaseDecreaseInOtherReceivables': ['其他應收款變動'],
  'us-gaap:IncreaseDecreaseInInventories': ['存貨（增加）減少'],
  'us-gaap:IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets': ['預付費用及其他資產變動'],
  'us-gaap:IncreaseDecreaseInOtherOperatingAssets': ['其他營業資產變動'],
  'us-gaap:IncreaseDecreaseInOtherCurrentAssets': ['其他流動資產變動'],
  'us-gaap:IncreaseDecreaseInOtherNoncurrentAssets': ['其他非流動資產變動'],
  'us-gaap:IncreaseDecreaseInAccountsPayable': ['應付帳款增加（減少）'],
  'us-gaap:IncreaseDecreaseInAccountsPayableAndAccruedLiabilities': ['應付帳款及應計負債變動'],
  'us-gaap:IncreaseDecreaseInAccruedLiabilities': ['應計負債變動'],
  'us-gaap:IncreaseDecreaseInAccruedLiabilitiesAndOtherOperatingLiabilities': ['應計負債及其他營業負債變動'],
  'us-gaap:IncreaseDecreaseInIncomeTaxes': ['應付所得稅變動'],
  'us-gaap:IncreaseDecreaseInAccruedIncomeTaxesPayable': ['應付所得稅變動'],
  'us-gaap:IncreaseDecreaseInContractWithCustomerLiability': ['合約負債變動'],
  'us-gaap:IncreaseDecreaseInOtherOperatingLiabilities': ['其他營業負債變動'],
  'us-gaap:IncreaseDecreaseInOtherCurrentLiabilities': ['其他流動負債變動'],
  'us-gaap:IncreaseDecreaseInOtherNoncurrentLiabilities': ['其他非流動負債變動'],
  'us-gaap:IncreaseDecreaseInOtherCurrentAssetsAndLiabilitiesNet': ['其他流動資產及負債變動淨額'],
  'us-gaap:IncreaseDecreaseInOperatingCapital': ['營運資金變動'],
  'us-gaap:IncreaseDecreaseInFinancialInstrumentsUsedInOperatingActivities': ['營業用金融工具變動'],
  'us-gaap:IncreaseDecreaseInCashCollateralForBorrowedSecurities': ['借入證券現金擔保品變動'],
  'us-gaap:IncreaseDecreaseInTradingLiabilities': ['交易負債變動'],
  'us-gaap:PaymentsForOriginationAndPurchasesOfLoansHeldForSale': ['承作及購入待售放款'],
  'us-gaap:NetCashProvidedByUsedInOperatingActivities': ['營業活動之淨現金流入（流出）', '本業實際產生的現金'],

  // ---------- 現金流量表：投資活動 ----------
  'us-gaap:PaymentsToAcquirePropertyPlantAndEquipment': ['購置不動產、廠房及設備', '資本支出（CapEx）'],
  'us-gaap:PaymentsToAcquireProductiveAssets': ['購置生產性資產'],
  'us-gaap:ProceedsFromSaleOfPropertyPlantAndEquipment': ['處分不動產、廠房及設備價款'],
  'us-gaap:PaymentsToAcquireIntangibleAssets': ['購置無形資產'],
  'us-gaap:PaymentsToAcquireMarketableSecurities': ['購買有價證券'],
  'us-gaap:ProceedsFromSaleAndMaturityOfMarketableSecurities': ['有價證券出售及到期'],
  'us-gaap:PaymentsToAcquireAvailableForSaleSecuritiesDebt': ['購買備供出售債務證券'],
  'us-gaap:ProceedsFromMaturitiesPrepaymentsAndCallsOfAvailableForSaleSecurities': ['備供出售證券到期收回'],
  'us-gaap:ProceedsFromSaleOfAvailableForSaleSecuritiesDebt': ['出售備供出售債務證券'],
  'us-gaap:ProceedsFromSaleAndMaturityOfAvailableForSaleSecurities': ['備供出售證券出售及到期'],
  'us-gaap:PaymentsToAcquireHeldToMaturitySecurities': ['購買持有至到期證券'],
  'us-gaap:ProceedsFromMaturitiesPrepaymentsAndCallsOfHeldToMaturitySecurities': ['持有至到期證券到期收回'],
  'us-gaap:PaymentsToAcquireShortTermInvestments': ['購買短期投資'],
  'us-gaap:ProceedsFromSaleMaturityAndCollectionOfShorttermInvestments': ['短期投資出售及到期'],
  'us-gaap:PaymentsToAcquireOtherInvestments': ['購買其他投資'],
  'us-gaap:ProceedsFromSaleAndMaturityOfOtherInvestments': ['其他投資出售及到期'],
  'us-gaap:PaymentsToAcquireInvestments': ['購買投資'],
  'us-gaap:PaymentsToAcquireEquityMethodInvestments': ['購買權益法投資'],
  'us-gaap:PaymentsToAcquireBusinessesNetOfCashAcquired': ['收購事業（扣除取得之現金）'],
  'us-gaap:ProceedsFromSalesOfBusinessAffiliateAndProductiveAssets': ['處分事業及生產性資產價款'],
  'us-gaap:ProceedsFromSaleOfFinanceReceivables': ['出售應收融資款'],
  'us-gaap:ProceedsFromSaleAndCollectionOfReceivables': ['出售及收回應收款'],
  'us-gaap:ProceedsFromPaymentsForFederalFundsSoldAndSecuritiesPurchasedUnderAgreementsToResellNet': ['拆放同業及附賣回證券淨變動'],
  'us-gaap:PaymentsForProceedsFromOtherInvestingActivities': ['其他投資活動'],
  'us-gaap:NetCashProvidedByUsedInInvestingActivities': ['投資活動之淨現金流入（流出）'],

  // ---------- 現金流量表：籌資活動 ----------
  'us-gaap:ProceedsFromIssuanceOfCommonStock': ['發行普通股'],
  'us-gaap:ProceedsFromStockPlans': ['員工認股計畫收款'],
  'us-gaap:ProceedsFromIssuanceOfSharesUnderIncentiveAndShareBasedCompensationPlansIncludingStockOptions': ['員工認股權及股份基礎給付計畫發行股票'],
  'us-gaap:ProceedsFromIssuanceOfConvertiblePreferredStock': ['發行可轉換特別股'],
  'us-gaap:ProceedsFromIssuanceOfPreferredStockAndPreferenceStock': ['發行特別股'],
  'us-gaap:PaymentsForRepurchaseOfCommonStock': ['買回普通股', '庫藏股買回支出'],
  'us-gaap:PaymentsForRepurchaseOfRedeemablePreferredStock': ['贖回特別股'],
  'us-gaap:PaymentsRelatedToTaxWithholdingForShareBasedCompensation': ['股份基礎給付代扣稅款支付'],
  'us-gaap:PaymentsOfDividends': ['支付股利'],
  'us-gaap:PaymentsOfDividendsCommonStock': ['支付普通股股利'],
  'us-gaap:PaymentsOfOrdinaryDividends': ['支付股利'],
  'us-gaap:PaymentsOfDividendsMinorityInterest': ['支付非控制權益股利'],
  'us-gaap:ProceedsFromIssuanceOfDebt': ['舉借債務'],
  'us-gaap:ProceedsFromDebtNetOfIssuanceCosts': ['舉借債務（扣除發行成本）'],
  'us-gaap:ProceedsFromIssuanceOfLongTermDebt': ['舉借長期債務'],
  'us-gaap:ProceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': ['發行長期債務及資本證券淨額'],
  'us-gaap:RepaymentsOfLongTermDebt': ['償還長期債務'],
  'us-gaap:RepaymentsOfLongTermDebtAndCapitalSecurities': ['償還長期債務及資本證券'],
  'us-gaap:RepaymentsOfDebtAndCapitalLeaseObligations': ['償還債務及租賃負債'],
  'us-gaap:RepaymentsOfConvertibleDebt': ['償還可轉換債務'],
  'us-gaap:ProceedsFromShortTermDebt': ['舉借短期債務'],
  'us-gaap:RepaymentsOfShortTermDebt': ['償還短期債務'],
  'us-gaap:ProceedsFromRepaymentsOfShortTermDebtMaturingInThreeMonthsOrLess': ['三個月內到期短期債務淨變動'],
  'us-gaap:ProceedsFromDebtMaturingInMoreThanThreeMonths': ['舉借三個月以上債務'],
  'us-gaap:RepaymentsOfDebtMaturingInMoreThanThreeMonths': ['償還三個月以上債務'],
  'us-gaap:ProceedsFromShortTermDebtMaturingInMoreThanThreeMonths': ['舉借三個月以上短期債務'],
  'us-gaap:RepaymentsOfShortTermDebtMaturingInMoreThanThreeMonths': ['償還三個月以上短期債務'],
  'us-gaap:ProceedsFromRepaymentsOfCommercialPaper': ['商業本票淨變動'],
  'us-gaap:ProceedsFromRepaymentsOfOtherDebt': ['其他債務淨變動'],
  'us-gaap:PaymentsOfDebtIssuanceCosts': ['支付債務發行成本'],
  'us-gaap:FinanceLeasePrincipalPayments': ['融資租賃本金償還'],
  'us-gaap:PaymentForContingentConsiderationLiabilityFinancingActivities': ['支付或有對價'],
  'us-gaap:ProceedsFromMinorityShareholders': ['非控制權益出資'],
  'us-gaap:PaymentsToMinorityShareholders': ['支付予非控制權益'],
  'us-gaap:ProceedsFromPaymentsToMinorityShareholders': ['與非控制權益之收付淨額'],
  'us-gaap:IncreaseDecreaseInDeposits': ['存款淨變動'],
  'us-gaap:IncreaseDecreaseInFederalFundsPurchasedAndSecuritiesSoldUnderAgreementsToRepurchaseNet': ['拆入同業及附買回證券淨變動'],
  'us-gaap:ProceedsFromPaymentsForOtherFinancingActivities': ['其他籌資活動'],
  'us-gaap:NetCashProvidedByUsedInFinancingActivities': ['籌資活動之淨現金流入（流出）'],

  // ---------- 現金流量表：其他 ----------
  'us-gaap:EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents': ['匯率變動對現金之影響'],
  'us-gaap:EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations': ['匯率變動對現金之影響'],
  'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect': ['本期現金及約當現金增加（減少）'],
  'us-gaap:IncomeTaxesPaidNet': ['支付所得稅'],
  'us-gaap:InterestPaidNet': ['支付利息'],
  'us-gaap:InterestPaid': ['支付利息'],
  'us-gaap:InterestPaidCapitalized': ['資本化利息'],
  'us-gaap:CapitalExpendituresIncurredButNotYetPaid': ['已發生尚未支付之資本支出'],
  'us-gaap:RightOfUseAssetObtainedInExchangeForOperatingLeaseLiability': ['取得營業租賃使用權資產'],
  'us-gaap:RightOfUseAssetObtainedInExchangeForFinanceLeaseLiability': ['取得融資租賃使用權資產'],
  'us-gaap:NoncashOrPartNoncashAcquisitionValueOfAssetsAcquired1': ['非現金取得之資產'],

  // ---------- IFRS：資產負債表 ----------
  'ifrs-full:StatementOfFinancialPositionAbstract': ['資產負債表'],
  'ifrs-full:AssetsAbstract': ['資產'],
  'ifrs-full:CurrentAssetsAbstract': ['流動資產'],
  'ifrs-full:NoncurrentAssetsAbstract': ['非流動資產'],
  'ifrs-full:EquityAndLiabilitiesAbstract': ['負債及權益'],
  'ifrs-full:CurrentLiabilitiesAbstract': ['流動負債'],
  'ifrs-full:NoncurrentLiabilitiesAbstract': ['非流動負債'],
  'ifrs-full:EquityAbstract': ['權益'],
  'ifrs-full:RetainedEarningsAbstract': ['保留盈餘'],
  'ifrs-full:CashAndCashEquivalents': ['現金及約當現金'],
  'ifrs-full:CurrentFinancialAssetsAtFairValueThroughProfitOrLoss': ['透過損益按公允價值衡量之金融資產—流動'],
  'ifrs-full:CurrentFinancialAssetsAtFairValueThroughOtherComprehensiveIncome': ['透過其他綜合損益按公允價值衡量之金融資產—流動'],
  'ifrs-full:CurrentFinancialAssetsAtAmortisedCost': ['按攤銷後成本衡量之金融資產—流動'],
  'ifrs-full:CurrentTradeReceivables': ['應收帳款'],
  'ifrs-full:TradeAndOtherCurrentReceivablesDueFromRelatedParties': ['應收關係人款項'],
  'ifrs-full:Inventories': ['存貨'],
  'ifrs-full:OtherCurrentFinancialAssets': ['其他流動金融資產'],
  'ifrs-full:OtherCurrentAssets': ['其他流動資產'],
  'ifrs-full:CurrentAssets': ['流動資產合計'],
  'ifrs-full:NoncurrentFinancialAssetsAtFairValueThroughProfitOrLoss': ['透過損益按公允價值衡量之金融資產—非流動'],
  'ifrs-full:NoncurrentFinancialAssetsAtFairValueThroughOtherComprehensiveIncome': ['透過其他綜合損益按公允價值衡量之金融資產—非流動'],
  'ifrs-full:NoncurrentFinancialAssetsAtAmortisedCost': ['按攤銷後成本衡量之金融資產—非流動'],
  'ifrs-full:InvestmentAccountedForUsingEquityMethod': ['採用權益法之投資'],
  'ifrs-full:PropertyPlantAndEquipment': ['不動產、廠房及設備'],
  'ifrs-full:RightofuseAssets': ['使用權資產'],
  'ifrs-full:IntangibleAssetsAndGoodwill': ['無形資產及商譽'],
  'ifrs-full:DeferredTaxAssets': ['遞延所得稅資產'],
  'ifrs-full:LongtermDeposits': ['存出保證金'],
  'ifrs-full:OtherNoncurrentAssets': ['其他非流動資產'],
  'ifrs-full:NoncurrentAssets': ['非流動資產合計'],
  'ifrs-full:Assets': ['資產總額'],
  'ifrs-full:CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLoss': ['透過損益按公允價值衡量之金融負債—流動'],
  'ifrs-full:TradeAndOtherCurrentPayablesToTradeSuppliers': ['應付帳款'],
  'ifrs-full:TradeAndOtherCurrentPayablesToRelatedParties': ['應付關係人款項'],
  'ifrs-full:ShorttermEmployeeBenefitsAccruals': ['應付員工福利'],
  'ifrs-full:CurrentPayablesForPurchaseOfNoncurrentAssets': ['應付設備款'],
  'ifrs-full:CurrentDividendPayables': ['應付股利'],
  'ifrs-full:CurrentTaxLiabilitiesCurrent': ['當期所得稅負債'],
  'ifrs-full:CurrentPortionOfLongtermBorrowings': ['一年內到期之長期借款'],
  'ifrs-full:CurrentAccruedExpensesAndOtherCurrentLiabilities': ['應付費用及其他流動負債'],
  'ifrs-full:CurrentLiabilities': ['流動負債合計'],
  'ifrs-full:NoncurrentPortionOfNoncurrentBondsIssued': ['應付公司債'],
  'ifrs-full:LongtermBorrowings': ['長期借款'],
  'ifrs-full:DeferredTaxLiabilities': ['遞延所得稅負債'],
  'ifrs-full:NoncurrentLeaseLiabilities': ['租賃負債—非流動'],
  'ifrs-full:NoncurrentRecognisedLiabilitiesDefinedBenefitPlan': ['淨確定福利負債'],
  'ifrs-full:NoncurrentWarrantLiability': ['認股權證負債'],
  'ifrs-full:OtherNoncurrentLiabilities': ['其他非流動負債'],
  'ifrs-full:NoncurrentLiabilities': ['非流動負債合計'],
  'ifrs-full:Liabilities': ['負債總額'],
  'ifrs-full:IssuedCapital': ['股本'],
  'ifrs-full:SharePremium': ['股本溢價'],
  'ifrs-full:CapitalReserve': ['資本公積'],
  'ifrs-full:RetainedEarnings': ['保留盈餘'],
  'ifrs-full:OtherReserves': ['其他權益'],
  'ifrs-full:EquityAttributableToOwnersOfParent': ['歸屬於母公司業主之權益'],
  'ifrs-full:NoncontrollingInterests': ['非控制權益'],
  'ifrs-full:Equity': ['權益總額'],
  'ifrs-full:EquityAndLiabilities': ['負債及權益總額'],
  'ifrs-full:NumberOfSharesOutstanding': ['流通在外股數'],

  // ---------- IFRS：損益表 ----------
  'ifrs-full:IncomeStatementAbstract': ['損益'],
  'ifrs-full:ExpenseByNatureAbstract': ['營業費用'],
  'ifrs-full:OtherComprehensiveIncomeAbstract': ['其他綜合損益'],
  'ifrs-full:ComponentsOfOtherComprehensiveIncomeThatWillNotBeReclassifiedToProfitOrLossNetOfTaxAbstract': ['不重分類至損益之項目'],
  'ifrs-full:ComponentsOfOtherComprehensiveIncomeThatWillBeReclassifiedToProfitOrLossNetOfTaxAbstract': ['後續可能重分類至損益之項目'],
  'ifrs-full:ProfitLossAttributableToAbstract': ['淨利歸屬於'],
  'ifrs-full:ComprehensiveIncomeAttributableToAbstract': ['綜合損益歸屬於'],
  'ifrs-full:EarningsPerShareAbstract': ['每股盈餘'],
  'ifrs-full:RevenueFromContractsWithCustomers': ['營業收入'],
  'ifrs-full:CostOfSales': ['營業成本'],
  'ifrs-full:GrossProfit': ['營業毛利'],
  'ifrs-full:ResearchAndDevelopmentExpense': ['研究發展費用'],
  'ifrs-full:GeneralAndAdministrativeExpense': ['管理費用'],
  'ifrs-full:SalesAndMarketingExpense': ['推銷費用'],
  'ifrs-full:OperatingExpenseExcludingCostOfSales': ['營業費用合計'],
  'ifrs-full:OtherOperatingIncomeExpense': ['其他營業收益及費損淨額'],
  'ifrs-full:ProfitLossFromOperatingActivities': ['營業淨利'],
  'ifrs-full:ShareOfProfitLossOfAssociatesAccountedForUsingEquityMethod': ['採用權益法認列之關聯企業損益份額'],
  'ifrs-full:RevenueFromInterest': ['利息收入'],
  'ifrs-full:OtherIncome': ['其他收入'],
  'ifrs-full:GainsLossesOnExchangeDifferencesOnTranslationRecognisedInProfitOrLoss': ['外幣兌換損益'],
  'ifrs-full:FinanceCosts': ['財務成本'],
  'ifrs-full:OtherGainsLosses': ['其他利益及損失'],
  'ifrs-full:ProfitLossBeforeTax': ['稅前淨利'],
  'ifrs-full:IncomeTaxExpenseContinuingOperations': ['所得稅費用'],
  'ifrs-full:ProfitLoss': ['本期淨利'],
  'ifrs-full:OtherComprehensiveIncomeBeforeTaxGainsLossesOnRemeasurementsOfDefinedBenefitPlans': ['確定福利計畫再衡量數'],
  'ifrs-full:OtherComprehensiveIncomeBeforeTaxGainsLossesFromInvestmentsInEquityInstruments': ['透過其他綜合損益按公允價值衡量之權益工具投資未實現評價損益'],
  'ifrs-full:OtherComprehensiveIncomeBeforeTaxGainsLossesOnHedgingInstrumentsThatHedgeInvestmentsInEquityInstruments': ['避險權益工具投資之避險工具損益'],
  'ifrs-full:ShareOfOtherComprehensiveIncomeOfAssociatesAndJointVenturesAccountedForUsingEquityMethodThatWillNotBeReclassifiedToProfitOrLossBeforeTax': ['採用權益法認列之關聯企業其他綜合損益份額—不重分類'],
  'ifrs-full:IncomeTaxRelatingToComponentsOfOtherComprehensiveIncomeThatWillNotBeReclassifiedToProfitOrLoss': ['不重分類項目之所得稅'],
  'ifrs-full:OtherComprehensiveIncomeThatWillNotBeReclassifiedToProfitOrLossNetOfTax': ['不重分類至損益之項目合計'],
  'ifrs-full:OtherComprehensiveIncomeNetOfTaxExchangeDifferencesOnTranslation': ['國外營運機構財務報表換算之兌換差額'],
  'ifrs-full:OtherComprehensiveIncomeNetOfTaxHedgesOfNetInvestmentsInForeignOperations': ['國外營運機構淨投資避險'],
  'ifrs-full:ShareOfOtherComprehensiveIncomeOfAssociatesAndJointVenturesAccountedForUsingEquityMethodThatWillBeReclassifiedToProfitOrLossNetOfTax': ['採用權益法認列之關聯企業其他綜合損益份額—可能重分類'],
  'ifrs-full:OtherComprehensiveIncomeThatWillBeReclassifiedToProfitOrLossNetOfTax': ['後續可能重分類至損益之項目合計'],
  'ifrs-full:OtherComprehensiveIncome': ['其他綜合損益（稅後）'],
  'ifrs-full:ComprehensiveIncome': ['本期綜合損益總額'],
  'ifrs-full:ProfitLossAttributableToOwnersOfParent': ['淨利歸屬於母公司業主'],
  'ifrs-full:ProfitLossAttributableToNoncontrollingInterests': ['淨利歸屬於非控制權益'],
  'ifrs-full:ComprehensiveIncomeAttributableToOwnersOfParent': ['綜合損益歸屬於母公司業主'],
  'ifrs-full:ComprehensiveIncomeAttributableToNoncontrollingInterests': ['綜合損益歸屬於非控制權益'],
  'ifrs-full:BasicEarningsLossPerShare': ['基本每股盈餘'],
  'ifrs-full:DilutedEarningsLossPerShare': ['稀釋每股盈餘'],

  // ---------- IFRS：權益變動表 ----------
  'ifrs-full:StatementOfChangesInEquityAbstract': ['權益變動表'],
  'ifrs-full:ChangesInNumberOfSharesOutstandingAbstract': ['流通在外股數變動'],
  'ifrs-full:ChangesInEquityAbstract': ['權益變動'],
  'ifrs-full:NumberOfShareOptionsExercisedInSharebasedPaymentArrangement': ['員工認股權執行股數'],
  'ifrs-full:DividendsPaid': ['分配股利'],
  'ifrs-full:IncreaseDecreaseThroughAppropriationOfRetainedEarnings': ['盈餘分配'],
  'ifrs-full:IncreaseDecreaseThroughSharebasedPaymentTransactions': ['股份基礎給付交易'],
  'ifrs-full:PurchaseOfTreasuryShares': ['買回庫藏股'],
  'ifrs-full:CancellationOfTreasuryShares': ['註銷庫藏股'],
  'ifrs-full:IncreaseDecreaseThroughDisposalOfSubsidiary': ['處分子公司'],
  'ifrs-full:IncreaseDecreaseThroughChangeInEquityOfSubsidiaries': ['子公司權益變動'],
  'ifrs-full:IncreaseDecreaseThroughTransactionsWithOwners': ['與業主之交易'],
  'ifrs-full:IncreaseDecreaseThroughChangesInOwnershipInterestsInSubsidiariesThatDoNotResultInLossOfControl': ['未喪失控制之子公司所有權變動'],

  // ---------- IFRS：現金流量表 ----------
  'ifrs-full:StatementOfCashFlowsAbstract': ['現金流量表'],
  'ifrs-full:CashFlowsFromUsedInOperatingActivitiesAbstract': ['營業活動之現金流量'],
  'ifrs-full:AdjustmentsForReconcileProfitLossAbstract': ['調整項目'],
  'ifrs-full:CashFlowsFromUsedInInvestingActivitiesAbstract': ['投資活動之現金流量'],
  'ifrs-full:CashFlowsFromUsedInFinancingActivitiesAbstract': ['籌資活動之現金流量'],
  'ifrs-full:AdjustmentsForDepreciationExpense': ['折舊費用'],
  'ifrs-full:AdjustmentsForAmortisationExpense': ['攤銷費用'],
  'ifrs-full:AdjustmentsForImpairmentLossesReversalOfImpairmentLossesRecognisedInProfitOrLossFinancialAssets': ['金融資產減損損失（迴轉利益）'],
  'ifrs-full:AdjustmentsForFinanceCosts': ['財務成本'],
  'ifrs-full:AdjustmentsForUndistributedProfitsOfAssociates': ['採用權益法認列之關聯企業損益份額'],
  'ifrs-full:AdjustmentsForInterestIncome': ['利息收入'],
  'ifrs-full:AdjustmentsForSharebasedPayments': ['股份基礎給付酬勞成本'],
  'ifrs-full:AdjustmentsForGainLossOnDisposalsPropertyPlantAndEquipment': ['處分不動產、廠房及設備損益'],
  'ifrs-full:AdjustmentsForImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLossPropertyPlantAndEquipment': ['不動產、廠房及設備減損損失'],
  'ifrs-full:AdjustmentsForUnrealisedForeignExchangeLossesGains': ['未實現外幣兌換損益'],
  'ifrs-full:AdjustmentsForDividendIncome': ['股利收入'],
  'ifrs-full:OtherAdjustmentsToReconcileProfitLoss': ['其他調整項目'],
  'ifrs-full:AdjustmentsForDecreaseIncreaseInTradeAndOtherReceivables': ['應收款項（增加）減少'],
  'ifrs-full:AdjustmentsForDecreaseIncreaseInInventories': ['存貨（增加）減少'],
  'ifrs-full:AdjustmentsForDecreaseIncreaseInOtherFinancialAssets': ['其他金融資產（增加）減少'],
  'ifrs-full:AdjustmentsForDecreaseIncreaseInOtherCurrentAssets': ['其他流動資產（增加）減少'],
  'ifrs-full:AdjustmentsForIncreaseDecreaseInTradeAccountPayable': ['應付帳款增加（減少）'],
  'ifrs-full:CashFlowsFromUsedInOperations': ['營運產生之現金流入'],
  'ifrs-full:IncomeTaxesPaidRefundClassifiedAsOperatingActivities': ['支付之所得稅'],
  'ifrs-full:CashFlowsFromUsedInOperatingActivities': ['營業活動之淨現金流入（流出）'],
  'ifrs-full:PurchaseOfFinancialAssetsMeasuredAtFairValueThroughProfitOrLossClassifiedAsInvestingActivities': ['取得透過損益按公允價值衡量之金融資產'],
  'ifrs-full:PurchaseOfFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncomeClassifiedAsInvestingActivities': ['取得透過其他綜合損益按公允價值衡量之金融資產'],
  'ifrs-full:PurchaseOfFinancialAssetsMeasuredAtAmortisedCostClassifiedAsInvestingActivities': ['取得按攤銷後成本衡量之金融資產'],
  'ifrs-full:PurchaseOfInterestsInInvestmentsAccountedForUsingEquityMethod': ['取得採用權益法之投資'],
  'ifrs-full:PurchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities': ['取得不動產、廠房及設備', '資本支出'],
  'ifrs-full:PurchaseOfIntangibleAssetsClassifiedAsInvestingActivities': ['取得無形資產'],
  'ifrs-full:ProceedsFromSalesOrMaturityOfFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncomeClassifiedAsInvestingActivities': ['處分或到期透過其他綜合損益按公允價值衡量之金融資產'],
  'ifrs-full:ProceedsFromSalesOrMaturityOfFinancialAssetsMeasuredAtAmortisedCostClassifiedAsInvestingActivities': ['處分或到期按攤銷後成本衡量之金融資產'],
  'ifrs-full:ProceedsFromSalesOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities': ['處分不動產、廠房及設備'],
  'ifrs-full:ProceedsFromSalesOfIntangibleAssetsClassifiedAsInvestingActivities': ['處分無形資產'],
  'ifrs-full:InterestReceivedClassifiedAsInvestingActivities': ['收取之利息'],
  'ifrs-full:DividendsReceivedClassifiedAsInvestingActivities': ['收取之股利'],
  'ifrs-full:DividendsReceivedFromInvestmentsAccountedForUsingEquityMethodClassifiedAsInvestingActivities': ['收取採用權益法投資之股利'],
  'ifrs-full:CashFlowsFromUsedInInvestingActivities': ['投資活動之淨現金流入（流出）'],
  'ifrs-full:ProceedsFromIssueOfBondsNotesAndDebentures': ['發行公司債'],
  'ifrs-full:RepaymentsOfBondsNotesAndDebentures': ['償還公司債'],
  'ifrs-full:ProceedsFromNoncurrentBorrowings': ['舉借長期借款'],
  'ifrs-full:RepaymentsOfNoncurrentBorrowings': ['償還長期借款'],
  'ifrs-full:PaymentsForDebtIssueCosts': ['支付債務發行成本'],
  'ifrs-full:PaymentsToAcquireOrRedeemEntitysShares': ['買回庫藏股'],
  'ifrs-full:PaymentsOfLeaseLiabilitiesClassifiedAsFinancingActivities': ['租賃本金償還'],
  'ifrs-full:InterestPaidClassifiedAsFinancingActivities': ['支付之利息'],
  'ifrs-full:DividendsPaidClassifiedAsFinancingActivities': ['發放現金股利'],
  'ifrs-full:ProceedsFromChangesInOwnershipInterestsInSubsidiaries': ['子公司所有權變動收款'],
  'ifrs-full:ProceedsFromContributionsOfNoncontrollingInterests': ['非控制權益出資'],
  'ifrs-full:CashFlowsFromUsedInFinancingActivities': ['籌資活動之淨現金流入（流出）'],
  'ifrs-full:EffectOfExchangeRateChangesOnCashAndCashEquivalents': ['匯率變動對現金及約當現金之影響'],
  'ifrs-full:IncreaseDecreaseInCashAndCashEquivalents': ['本期現金及約當現金增加（減少）'],
};

const ALL = { ...T, ...MORE, ...CUSTOM };

function lookup(concept) {
  const hit = ALL[concept];
  if (hit) return { labelZh: hit[0], descriptionZh: hit[1] || DESCRIPTIONS[concept] || null };
  // a company's own extension element that reuses a standard name (abc:OperatingLeaseLiabilityCurrent)
  const i = concept.indexOf(':');
  if (i > 0 && !/^(us-gaap|ifrs-full|dei|srt):/.test(concept)) {
    const local = concept.slice(i + 1);
    for (const p of ['us-gaap', 'ifrs-full']) {
      const std = ALL[`${p}:${local}`];
      if (std) return { labelZh: std[0], descriptionZh: std[1] || DESCRIPTIONS[`${p}:${local}`] || null };
    }
  }
  return { labelZh: null, descriptionZh: null };
}

export function zhFor(concept) {
  return lookup(concept);
}

// Fill in Chinese names for a saved result whose line items predate the
// current dictionary (labels are stored with the parsed filing, so new
// translations would otherwise only reach freshly scraped filings).
export function applyZh(result) {
  const seen = new Set();
  const lists = [...(result.allStatements || []), ...Object.values(result.statements || {})].filter(Boolean);
  for (const stmt of lists) {
    if (seen.has(stmt)) continue;
    seen.add(stmt);
    for (const li of stmt.lineItems || []) {
      if (li.labelZh && li.descriptionZh) continue;
      const z = lookup(li.concept);
      if (!li.labelZh && z.labelZh) li.labelZh = z.labelZh;
      if (!li.descriptionZh && z.descriptionZh) li.descriptionZh = z.descriptionZh;
    }
  }
  return result;
}

export const zhCount = Object.keys(ALL).length;
